package com.example.projetofinal;

import android.os.Bundle;
import android.os.Parcelable;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonArrayRequest;
import com.android.volley.toolbox.Volley;
import com.example.projetofinal.ui.adapter.Adapter;
import com.example.projetofinal.ui.model.Cidade;
import com.example.projetofinal.ui.model.TipoCrime;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class DadosCidades extends Fragment implements Response.Listener<JSONArray>, Response.ErrorListener {
    private String url;
    List<Parcelable> cidades =  new ArrayList<>();
    List<TipoCrime> crimes =  new ArrayList<>();
    private RecyclerView rv;
    View root;
    public ArrayList<String> arrayCidades = new ArrayList();
    int totalCrimes;

    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        root = inflater.inflate(R.layout.fragment_dados_cidades, container, false);
        url = "https://babyier.rocks/uniritter/DadosCrimeRS2020_CrimesPorCidade.json";
        RequestQueue queue = Volley.newRequestQueue(getContext());
        JsonArrayRequest jsonArrayRequest = new JsonArrayRequest(Request.Method.GET, url, null,
                this, this);
        queue.add(jsonArrayRequest);

        return root;
    }

    @Override
    public void onResponse(JSONArray response) {
        try {
            getArrayCidades();

            for(int i = 0; i < response.length(); i++) {
                JSONObject json = null;
                json = response.getJSONObject(i);

                totalCrimes = 0;

                for (String cidade:arrayCidades) {
                    JSONObject jsonExt = json.getJSONObject(cidade);

                    crimes.add(new TipoCrime("VITIMAS DE HOMICIDIO DOLOSO",jsonExt.getInt("VITIMAS DE HOMICIDIO DOLOSO")));
                    totalCrimes += jsonExt.getInt("VITIMAS DE HOMICIDIO DOLOSO");
                    crimes.add(new TipoCrime("LATROCINIO",jsonExt.getInt("LATROCINIO")));
                    totalCrimes += jsonExt.getInt("LATROCINIO");
                    crimes.add(new TipoCrime("FURTOS",jsonExt.getInt("FURTOS")));
                    totalCrimes += jsonExt.getInt("FURTOS");
                    crimes.add(new TipoCrime("ABIGEATO",jsonExt.getInt("ABIGEATO")));
                    totalCrimes += jsonExt.getInt("ABIGEATO");
                    crimes.add(new TipoCrime("FURTO DE VEICULOS",jsonExt.getInt("FURTO DE VEICULOS")));
                    totalCrimes += jsonExt.getInt("FURTO DE VEICULOS");
                    crimes.add(new TipoCrime("ROUBOS",jsonExt.getInt("ROUBOS")));
                    totalCrimes += jsonExt.getInt("ROUBOS");
                    crimes.add(new TipoCrime("ESTELIONATO",jsonExt.getInt("ESTELIONATO")));
                    totalCrimes += jsonExt.getInt("ESTELIONATO");
                    crimes.add(new TipoCrime("POSSE DE ENTORPECENTES",jsonExt.getInt("POSSE DE ENTORPECENTES")));
                    totalCrimes += jsonExt.getInt("POSSE DE ENTORPECENTES");
                    crimes.add(new TipoCrime("VITIMAS DE LESAO CORPORAL SEGUIDA DE MORTE",jsonExt.getInt("VITIMAS DE LESAO CORPORAL SEGUIDA DE MORTE")));
                    totalCrimes += jsonExt.getInt("VITIMAS DE LESAO CORPORAL SEGUIDA DE MORTE");

                    Cidade obj = new Cidade(cidade,crimes,totalCrimes);
                    obj.getCidadeNome();
                    cidades.add(obj);

                    arrayCidades.remove(cidade);
                    break;
                }
            }

            rv = root.findViewById(R.id.RecyclerViewListApiCidades);
            rv.setLayoutManager(new LinearLayoutManager(getContext()));

            Adapter adapter = new Adapter(cidades, R.layout.content_cidades);
            rv.setAdapter(adapter);
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onErrorResponse(VolleyError error) {

    }

    public ArrayList<String> getArrayCidades() {
        arrayCidades.add("ACEGUA");
        arrayCidades.add("AGUA SANTA");
        arrayCidades.add("AGUDO");
        arrayCidades.add("AJURICABA");
        arrayCidades.add("ALECRIM");
        arrayCidades.add("ALEGRETE");
        arrayCidades.add("ALEGRIA");
        arrayCidades.add("ALMIRANTE TAMANDARE DO SUL");
        arrayCidades.add("ALPESTRE");
        arrayCidades.add("ALTO ALEGRE");
        arrayCidades.add("ALTO FELIZ");
        arrayCidades.add("ALVORADA");
        arrayCidades.add("AMARAL FERRADOR");
        arrayCidades.add("AMETISTA DO SUL");
        arrayCidades.add("ANDRE DA ROCHA");
        arrayCidades.add("ANTA GORDA");
        arrayCidades.add("ANTONIO PRADO");
        arrayCidades.add("ARAMBARE");
        arrayCidades.add("ARARICA");
        arrayCidades.add("ARATIBA");
        arrayCidades.add("ARROIO DO MEIO");
        arrayCidades.add("ARROIO DO PADRE");
        arrayCidades.add("ARROIO DO SAL");
        arrayCidades.add("ARROIO DO TIGRE");
        arrayCidades.add("ARROIO DOS RATOS");
        arrayCidades.add("ARROIO GRANDE");
        arrayCidades.add("ARVOREZINHA");
        arrayCidades.add("AUGUSTO PESTANA");
        arrayCidades.add("AUREA");
        arrayCidades.add("BAGE");
        arrayCidades.add("BALNEARIO PINHAL");
        arrayCidades.add("BARAO");
        arrayCidades.add("BARAO DE COTEGIPE");
        arrayCidades.add("BARAO DO TRIUNFO");
        arrayCidades.add("BARRA DO GUARITA");
        arrayCidades.add("BARRA DO QUARAI");
        arrayCidades.add("BARRA DO RIBEIRO");
        arrayCidades.add("BARRA DO RIO AZUL");
        arrayCidades.add("BARRA FUNDA");
        arrayCidades.add("BARRACAO");
        arrayCidades.add("BARROS CASSAL");
        arrayCidades.add("BENJAMIN CONSTANT DO SUL");
        arrayCidades.add("BENTO GONCALVES");
        arrayCidades.add("BOA VISTA DAS MISSOES");
        arrayCidades.add("BOA VISTA DO BURICA");
        arrayCidades.add("BOA VISTA DO CADEADO");
        arrayCidades.add("BOA VISTA DO INCRA");
        arrayCidades.add("BOA VISTA DO SUL");
        arrayCidades.add("BOM JESUS");
        arrayCidades.add("BOM PRINCIPIO");
        arrayCidades.add("BOM PROGRESSO");
        arrayCidades.add("BOM RETIRO DO SUL");
        arrayCidades.add("BOQUEIRAO DO LEAO");
        arrayCidades.add("BOSSOROCA");
        arrayCidades.add("BOZANO");
        arrayCidades.add("BRAGA");
        arrayCidades.add("BROCHIER");
        arrayCidades.add("BUTIA");
        arrayCidades.add("CACAPAVA DO SUL");
        arrayCidades.add("CACEQUI");
        arrayCidades.add("CACHOEIRA DO SUL");
        arrayCidades.add("CACHOEIRINHA");
        arrayCidades.add("CACIQUE DOBLE");
        arrayCidades.add("CAIBATE");
        arrayCidades.add("CAICARA");
        arrayCidades.add("CAMAQUA");
        arrayCidades.add("CAMARGO");
        arrayCidades.add("CAMBARA DO SUL");
        arrayCidades.add("CAMPESTRE DA SERRA");
        arrayCidades.add("CAMPINA DAS MISSOES");
        arrayCidades.add("CAMPINAS DO SUL");
        arrayCidades.add("CAMPO BOM");
        arrayCidades.add("CAMPO NOVO");
        arrayCidades.add("CAMPOS BORGES");
        arrayCidades.add("CANDELARIA");
        arrayCidades.add("CANDIDO GODOI");
        arrayCidades.add("CANDIOTA");
        arrayCidades.add("CANELA");
        arrayCidades.add("CANGUCU");
        arrayCidades.add("CANOAS");
        arrayCidades.add("CANUDOS DO VALE");
        arrayCidades.add("CAPAO BONITO DO SUL");
        arrayCidades.add("CAPAO DA CANOA");
        arrayCidades.add("CAPAO DO CIPO");
        arrayCidades.add("CAPAO DO LEAO");
        arrayCidades.add("CAPELA DE SANTANA");
        arrayCidades.add("CAPITAO");
        arrayCidades.add("CAPIVARI DO SUL");
        arrayCidades.add("CARAA");
        arrayCidades.add("CARAZINHO");
        arrayCidades.add("CARLOS BARBOSA");
        arrayCidades.add("CARLOS GOMES");
        arrayCidades.add("CASCA");
        arrayCidades.add("CASEIROS");
        arrayCidades.add("CATUIPE");
        arrayCidades.add("CAXIAS DO SUL");
        arrayCidades.add("CENTENARIO");
        arrayCidades.add("CERRITO");
        arrayCidades.add("CERRO BRANCO");
        arrayCidades.add("CERRO GRANDE");
        arrayCidades.add("CERRO GRANDE DO SUL");
        arrayCidades.add("CERRO LARGO");
        arrayCidades.add("CHAPADA");
        arrayCidades.add("CHARQUEADAS");
        arrayCidades.add("CHARRUA");
        arrayCidades.add("CHIAPETTA");
        arrayCidades.add("CHUI");
        arrayCidades.add("CHUVISCA");
        arrayCidades.add("CIDREIRA");
        arrayCidades.add("CIRIACO");
        arrayCidades.add("COLINAS");
        arrayCidades.add("COLORADO");
        arrayCidades.add("CONDOR");
        arrayCidades.add("CONSTANTINA");
        arrayCidades.add("COQUEIRO BAIXO");
        arrayCidades.add("COQUEIROS DO SUL");
        arrayCidades.add("CORONEL BARROS");
        arrayCidades.add("CORONEL BICACO");
        arrayCidades.add("CORONEL PILAR");
        arrayCidades.add("COTIPORA");
        arrayCidades.add("COXILHA");
        arrayCidades.add("CRISSIUMAL");
        arrayCidades.add("CRISTAL");
        arrayCidades.add("CRISTAL DO SUL");
        arrayCidades.add("CRUZ ALTA");
        arrayCidades.add("CRUZALTENSE");
        arrayCidades.add("CRUZEIRO DO SUL");
        arrayCidades.add("DAVID CANABARRO");
        arrayCidades.add("DERRUBADAS");
        arrayCidades.add("DEZESSEIS DE NOVEMBRO");
        arrayCidades.add("DILERMANDO DE AGUIAR");
        arrayCidades.add("DOIS IRMAOS");
        arrayCidades.add("DOIS IRMAOS DAS MISSOES");
        arrayCidades.add("DOIS LAJEADOS");
        arrayCidades.add("DOM FELICIANO");
        arrayCidades.add("DOM PEDRITO");
        arrayCidades.add("DOM PEDRO DE ALCANTARA");
        arrayCidades.add("DONA FRANCISCA");
        arrayCidades.add("DOUTOR RICARDO");
        arrayCidades.add("DR MAURICIO CARDOSO");
        arrayCidades.add("ELDORADO DO SUL");
        arrayCidades.add("ENCANTADO");
        arrayCidades.add("ENCRUZILHADA DO SUL");
        arrayCidades.add("ENGENHO VELHO");
        arrayCidades.add("ENTRE IJUIS");
        arrayCidades.add("ENTRE RIOS DO SUL");
        arrayCidades.add("EREBANGO");
        arrayCidades.add("ERECHIM");
        arrayCidades.add("ERNESTINA");
        arrayCidades.add("ERVAL GRANDE");
        arrayCidades.add("ERVAL SECO");
        arrayCidades.add("ESMERALDA");
        arrayCidades.add("ESPERANCA DO SUL");
        arrayCidades.add("ESPUMOSO");
        arrayCidades.add("ESTACAO");
        arrayCidades.add("ESTANCIA VELHA");
        arrayCidades.add("ESTEIO");
        arrayCidades.add("ESTRELA");
        arrayCidades.add("ESTRELA VELHA");
        arrayCidades.add("EUGENIO DE CASTRO");
        arrayCidades.add("FAGUNDES VARELA");
        arrayCidades.add("FARROUPILHA");
        arrayCidades.add("FAXINAL DO SOTURNO");
        arrayCidades.add("FAXINALZINHO");
        arrayCidades.add("FAZENDA VILA NOVA");
        arrayCidades.add("FELIZ");
        arrayCidades.add("FLORES DA CUNHA");
        arrayCidades.add("FLORIANO PEIXOTO");
        arrayCidades.add("FONTOURA XAVIER");
        arrayCidades.add("FORMIGUEIRO");
        arrayCidades.add("FORQUETINHA");
        arrayCidades.add("FORTALEZA DOS VALOS");
        arrayCidades.add("FREDERICO WESTPHALEN");
        arrayCidades.add("GARIBALDI");
        arrayCidades.add("GARRUCHOS");
        arrayCidades.add("GAURAMA");
        arrayCidades.add("GENERAL CAMARA");
        arrayCidades.add("GENTIL");
        arrayCidades.add("GETULIO VARGAS");
        arrayCidades.add("GIRUA");
        arrayCidades.add("GLORINHA");
        arrayCidades.add("GRAMADO");
        arrayCidades.add("GRAMADO DOS LOUREIROS");
        arrayCidades.add("GRAMADO XAVIER");
        arrayCidades.add("GRAVATAI");
        arrayCidades.add("GUABIJU");
        arrayCidades.add("GUAIBA");
        arrayCidades.add("GUAPORE");
        arrayCidades.add("GUARANI DAS MISSOES");
        arrayCidades.add("HARMONIA");
        arrayCidades.add("HERVAL");
        arrayCidades.add("HERVEIRAS");
        arrayCidades.add("HORIZONTINA");
        arrayCidades.add("HULHA NEGRA");
        arrayCidades.add("HUMAITA");
        arrayCidades.add("IBARAMA");
        arrayCidades.add("IBIACA");
        arrayCidades.add("IBIRAIARAS");
        arrayCidades.add("IBIRAPUITA");
        arrayCidades.add("IBIRUBA");
        arrayCidades.add("IGREJINHA");
        arrayCidades.add("IJUI");
        arrayCidades.add("ILOPOLIS");
        arrayCidades.add("IMBE");
        arrayCidades.add("IMIGRANTE");
        arrayCidades.add("INDEPENDENCIA");
        arrayCidades.add("INHACORA");
        arrayCidades.add("IPE");
        arrayCidades.add("IPIRANGA DO SUL");
        arrayCidades.add("IRAI");
        arrayCidades.add("ITAARA");
        arrayCidades.add("ITACURUBI");
        arrayCidades.add("ITAPUCA");
        arrayCidades.add("ITAQUI");
        arrayCidades.add("ITATI");
        arrayCidades.add("ITATIBA DO SUL");
        arrayCidades.add("IVORA");
        arrayCidades.add("IVOTI");
        arrayCidades.add("JABOTICABA");
        arrayCidades.add("JACUIZINHO");
        arrayCidades.add("JACUTINGA");
        arrayCidades.add("JAGUARAO");
        arrayCidades.add("JAGUARI");
        arrayCidades.add("JAQUIRANA");
        arrayCidades.add("JARI");
        arrayCidades.add("JOIA");
        arrayCidades.add("JULIO DE CASTILHOS");
        arrayCidades.add("LAGOA BONITA DO SUL");
        arrayCidades.add("LAGOA DOS TRES CANTOS");
        arrayCidades.add("LAGOA VERMELHA");
        arrayCidades.add("LAGOAO");
        arrayCidades.add("LAJEADO");
        arrayCidades.add("LAJEADO DO BUGRE");
        arrayCidades.add("LAVRAS DO SUL");
        arrayCidades.add("LIBERATO SALZANO");
        arrayCidades.add("LINDOLFO COLLOR");
        arrayCidades.add("LINHA NOVA");
        arrayCidades.add("MACAMBARA");
        arrayCidades.add("MACHADINHO");
        arrayCidades.add("MAMPITUBA");
        arrayCidades.add("MANOEL VIANA");
        arrayCidades.add("MAQUINE");
        arrayCidades.add("MARATA");
        arrayCidades.add("MARAU");
        arrayCidades.add("MARCELINO RAMOS");
        arrayCidades.add("MARIANA PIMENTEL");
        arrayCidades.add("MARIANO MORO");
        arrayCidades.add("MARQUES DE SOUZA");
        arrayCidades.add("MATA");
        arrayCidades.add("MATO CASTELHANO");
        arrayCidades.add("MATO LEITAO");
        arrayCidades.add("MATO QUEIMADO");
        arrayCidades.add("MAXIMILIANO DE ALMEIDA");
        arrayCidades.add("MINAS DO LEAO");
        arrayCidades.add("MIRAGUAI");
        arrayCidades.add("MONTAURI");
        arrayCidades.add("MONTE ALEGRE DOS CAMPOS");
        arrayCidades.add("MONTE BELO DO SUL");
        arrayCidades.add("MONTENEGRO");
        arrayCidades.add("MORMACO");
        arrayCidades.add("MORRINHOS DO SUL");
        arrayCidades.add("MORRO REDONDO");
        arrayCidades.add("MORRO REUTER");
        arrayCidades.add("MOSTARDAS");
        arrayCidades.add("MUCUM");
        arrayCidades.add("MUITOS CAPOES");
        arrayCidades.add("MULITERNO");
        arrayCidades.add("NAO-ME-TOQUE");
        arrayCidades.add("NICOLAU VERGUEIRO");
        arrayCidades.add("NONOAI");
        arrayCidades.add("NOVA ALVORADA");
        arrayCidades.add("NOVA ARACA");
        arrayCidades.add("NOVA BASSANO");
        arrayCidades.add("NOVA BOA VISTA");
        arrayCidades.add("NOVA BRESCIA");
        arrayCidades.add("NOVA CANDELARIA");
        arrayCidades.add("NOVA ESPERANCA DO SUL");
        arrayCidades.add("NOVA HARTZ");
        arrayCidades.add("NOVA PADUA");
        arrayCidades.add("NOVA PALMA");
        arrayCidades.add("NOVA PETROPOLIS");
        arrayCidades.add("NOVA PRATA");
        arrayCidades.add("NOVA RAMADA");
        arrayCidades.add("NOVA ROMA DO SUL");
        arrayCidades.add("NOVA SANTA RITA");
        arrayCidades.add("NOVO BARREIRO");
        arrayCidades.add("NOVO CABRAIS");
        arrayCidades.add("NOVO HAMBURGO");
        arrayCidades.add("NOVO MACHADO");
        arrayCidades.add("NOVO TIRADENTES");
        arrayCidades.add("NOVO XINGU");
        arrayCidades.add("OSORIO");
        arrayCidades.add("PAIM FILHO");
        arrayCidades.add("PALMARES DO SUL");
        arrayCidades.add("PALMEIRA DAS MISSOES");
        arrayCidades.add("PALMITINHO");
        arrayCidades.add("PANAMBI");
        arrayCidades.add("PANTANO GRANDE");
        arrayCidades.add("PARAI");
        arrayCidades.add("PARAISO DO SUL");
        arrayCidades.add("PARECI NOVO");
        arrayCidades.add("PAROBE");
        arrayCidades.add("PASSA SETE");
        arrayCidades.add("PASSO DO SOBRADO");
        arrayCidades.add("PASSO FUNDO");
        arrayCidades.add("PAULO BENTO");
        arrayCidades.add("PAVERAMA");
        arrayCidades.add("PEDRAS ALTAS");
        arrayCidades.add("PEDRO OSORIO");
        arrayCidades.add("PEJUCARA");
        arrayCidades.add("PELOTAS");
        arrayCidades.add("PICADA CAFE");
        arrayCidades.add("PINHAL");
        arrayCidades.add("PINHAL DA SERRA");
        arrayCidades.add("PINHAL GRANDE");
        arrayCidades.add("PINHEIRINHO DO VALE");
        arrayCidades.add("PINHEIRO MACHADO");
        arrayCidades.add("PINTO BANDEIRA");
        arrayCidades.add("PIRAPO");
        arrayCidades.add("PIRATINI");
        arrayCidades.add("PLANALTO");
        arrayCidades.add("POCO DAS ANTAS");
        arrayCidades.add("PONTAO");
        arrayCidades.add("PONTE PRETA");
        arrayCidades.add("PORTAO");
        arrayCidades.add("PORTO ALEGRE");
        arrayCidades.add("PORTO LUCENA");
        arrayCidades.add("PORTO MAUA");
        arrayCidades.add("PORTO VERA CRUZ");
        arrayCidades.add("PORTO XAVIER");
        arrayCidades.add("POUSO NOVO");
        arrayCidades.add("PRESIDENTE LUCENA");
        arrayCidades.add("PROGRESSO");
        arrayCidades.add("PROTASIO ALVES");
        arrayCidades.add("PUTINGA");
        arrayCidades.add("QUARAI");
        arrayCidades.add("QUATRO IRMAOS");
        arrayCidades.add("QUEVEDOS");
        arrayCidades.add("QUINZE DE NOVEMBRO");
        arrayCidades.add("REDENTORA");
        arrayCidades.add("RELVADO");
        arrayCidades.add("RESTINGA SECA");
        arrayCidades.add("RIO DOS INDIOS");
        arrayCidades.add("RIO GRANDE");
        arrayCidades.add("RIO PARDO");
        arrayCidades.add("RIOZINHO");
        arrayCidades.add("ROCA SALES");
        arrayCidades.add("RODEIO BONITO");
        arrayCidades.add("ROLADOR");
        arrayCidades.add("ROLANTE");
        arrayCidades.add("RONDA ALTA");
        arrayCidades.add("RONDINHA");
        arrayCidades.add("ROQUE GONZALES");
        arrayCidades.add("ROSARIO DO SUL");
        arrayCidades.add("SAGRADA FAMILIA");
        arrayCidades.add("SALDANHA MARINHO");
        arrayCidades.add("SALTO DO JACUI");
        arrayCidades.add("SALVADOR DAS MISSOES");
        arrayCidades.add("SALVADOR DO SUL");
        arrayCidades.add("SANANDUVA");
        arrayCidades.add("SANTA BARBARA DO SUL");
        arrayCidades.add("SANTA CECILIA DO SUL");
        arrayCidades.add("SANTA CLARA DO SUL");
        arrayCidades.add("SANTA CRUZ DO SUL");
        arrayCidades.add("SANTA MARGARIDA DO SUL");
        arrayCidades.add("SANTA MARIA");
        arrayCidades.add("SANTA MARIA DO HERVAL");
        arrayCidades.add("SANTA ROSA");
        arrayCidades.add("SANTA TEREZA");
        arrayCidades.add("SANTA VITORIA DO PALMAR");
        arrayCidades.add("SANTANA DA BOA VISTA");
        arrayCidades.add("SANTANA DO LIVRAMENTO");
        arrayCidades.add("SANTIAGO");
        arrayCidades.add("SANTO ANGELO");
        arrayCidades.add("SANTO ANTONIO DA PATRULHA");
        arrayCidades.add("SANTO ANTONIO DAS MISSOES");
        arrayCidades.add("SANTO ANTONIO DO PALMA");
        arrayCidades.add("SANTO ANTONIO DO PLANALTO");
        arrayCidades.add("SANTO AUGUSTO");
        arrayCidades.add("SANTO CRISTO");
        arrayCidades.add("SANTO EXPEDITO DO SUL");
        arrayCidades.add("SAO BORJA");
        arrayCidades.add("SAO DOMINGOS DO SUL");
        arrayCidades.add("SAO FRANCISCO DE ASSIS");
        arrayCidades.add("SAO FRANCISCO DE PAULA");
        arrayCidades.add("SAO GABRIEL");
        arrayCidades.add("SAO JERONIMO");
        arrayCidades.add("SAO JOAO DA URTIGA");
        arrayCidades.add("SAO JOAO DO POLESINE");
        arrayCidades.add("SAO JORGE");
        arrayCidades.add("SAO JOSE DAS MISSOES");
        arrayCidades.add("SAO JOSE DO HERVAL");
        arrayCidades.add("SAO JOSE DO HORTENCIO");
        arrayCidades.add("SAO JOSE DO INHACORA");
        arrayCidades.add("SAO JOSE DO NORTE");
        arrayCidades.add("SAO JOSE DO OURO");
        arrayCidades.add("SAO JOSE DO SUL");
        arrayCidades.add("SAO JOSE DOS AUSENTES");
        arrayCidades.add("SAO LEOPOLDO");
        arrayCidades.add("SAO LOURENCO DO SUL");
        arrayCidades.add("SAO LUIZ GONZAGA");
        arrayCidades.add("SAO MARCOS");
        arrayCidades.add("SAO MARTINHO");
        arrayCidades.add("SAO MARTINHO DA SERRA");
        arrayCidades.add("SAO MIGUEL DAS MISSOES");
        arrayCidades.add("SAO NICOLAU");
        arrayCidades.add("SAO PAULO DAS MISSOES");
        arrayCidades.add("SAO PEDRO DA SERRA");
        arrayCidades.add("SAO PEDRO DAS MISSOES");
        arrayCidades.add("SAO PEDRO DO BUTIA");
        arrayCidades.add("SAO PEDRO DO SUL");
        arrayCidades.add("SAO SEBASTIAO DO CAI");
        arrayCidades.add("SAO SEPE");
        arrayCidades.add("SAO VALENTIM");
        arrayCidades.add("SAO VALENTIM DO SUL");
        arrayCidades.add("SAO VALERIO DO SUL");
        arrayCidades.add("SAO VENDELINO");
        arrayCidades.add("SAO VICENTE DO SUL");
        arrayCidades.add("SAPIRANGA");
        arrayCidades.add("SAPUCAIA DO SUL");
        arrayCidades.add("SARANDI");
        arrayCidades.add("SEBERI");
        arrayCidades.add("SEDE NOVA");
        arrayCidades.add("SEGREDO");
        arrayCidades.add("SELBACH");
        arrayCidades.add("SENADOR SALGADO FILHO");
        arrayCidades.add("SENTINELA DO SUL");
        arrayCidades.add("SERAFINA CORREA");
        arrayCidades.add("SERIO");
        arrayCidades.add("SERTAO");
        arrayCidades.add("SERTAO SANTANA");
        arrayCidades.add("SETE DE SETEMBRO");
        arrayCidades.add("SEVERIANO DE ALMEIDA");
        arrayCidades.add("SILVEIRA MARTINS");
        arrayCidades.add("SINIMBU");
        arrayCidades.add("SOBRADINHO");
        arrayCidades.add("SOLEDADE");
        arrayCidades.add("TABAI");
        arrayCidades.add("TAPEJARA");
        arrayCidades.add("TAPERA");
        arrayCidades.add("TAPES");
        arrayCidades.add("TAQUARA");
        arrayCidades.add("TAQUARI");
        arrayCidades.add("TAQUARUCU DO SUL");
        arrayCidades.add("TAVARES");
        arrayCidades.add("TENENTE PORTELA");
        arrayCidades.add("TERRA DE AREIA");
        arrayCidades.add("TEUTONIA");
        arrayCidades.add("TIO HUGO");
        arrayCidades.add("TIRADENTES DO SUL");
        arrayCidades.add("TOROPI");
        arrayCidades.add("TORRES");
        arrayCidades.add("TRAMANDAI");
        arrayCidades.add("TRAVESSEIRO");
        arrayCidades.add("TRES ARROIOS");
        arrayCidades.add("TRES CACHOEIRAS");
        arrayCidades.add("TRES COROAS");
        arrayCidades.add("TRES DE MAIO");
        arrayCidades.add("TRES FORQUILHAS");
        arrayCidades.add("TRES PALMEIRAS");
        arrayCidades.add("TRES PASSOS");
        arrayCidades.add("TRINDADE DO SUL");
        arrayCidades.add("TRIUNFO");
        arrayCidades.add("TUCUNDUVA");
        arrayCidades.add("TUNAS");
        arrayCidades.add("TUPANCI DO SUL");
        arrayCidades.add("TUPANCIRETA");
        arrayCidades.add("TUPANDI");
        arrayCidades.add("TUPARENDI");
        arrayCidades.add("TURUCU");
        arrayCidades.add("UBIRETAMA");
        arrayCidades.add("UNIAO DA SERRA");
        arrayCidades.add("UNISTALDA");
        arrayCidades.add("URUGUAIANA");
        arrayCidades.add("VACARIA");
        arrayCidades.add("VALE DO SOL");
        arrayCidades.add("VALE REAL");
        arrayCidades.add("VALE VERDE");
        arrayCidades.add("VANINI");
        arrayCidades.add("VENANCIO AIRES");
        arrayCidades.add("VERA CRUZ");
        arrayCidades.add("VERANOPOLIS");
        arrayCidades.add("VESPASIANO CORREA");
        arrayCidades.add("VIADUTOS");
        arrayCidades.add("VIAMAO");
        arrayCidades.add("VICENTE DUTRA");
        arrayCidades.add("VICTOR GRAEFF");
        arrayCidades.add("VILA FLORES");
        arrayCidades.add("VILA LANGARO");
        arrayCidades.add("VILA MARIA");
        arrayCidades.add("VILA NOVA DO SUL");
        arrayCidades.add("VISTA ALEGRE");
        arrayCidades.add("VISTA ALEGRE DO PRATA");
        arrayCidades.add("VISTA GAUCHA");
        arrayCidades.add("VITORIA DAS MISSOES");
        arrayCidades.add("WESTFALIA");
        arrayCidades.add("XANGRI-LA");

        return arrayCidades;
    }
}